// Complete tool registry — source of truth for all 12 PDF tools.
// Each tool has: slug, name, description, icon (Lucide), category,
// accepted file types, multi-file support, and optional tool-specific options.

export const TOOLS = [
  {
    slug: 'merge-pdf',
    name: 'Merge PDF',
    desc: 'Combine multiple PDF files into one document in any order you choose.',
    shortDesc: 'Combine multiple PDFs into one.',
    icon: 'Combine',
    category: 'organize',
    accept: { 'application/pdf': ['.pdf'] },
    acceptLabel: '.pdf',
    multiple: true,
    minFiles: 2,
    options: [],
    outputExt: '.pdf',
    outputMime: 'application/pdf',
    color: '#3B82F6',
  },
  {
    slug: 'split-pdf',
    name: 'Split PDF',
    desc: 'Separate one page or a whole set into independent PDF files.',
    shortDesc: 'Break a PDF into separate files.',
    icon: 'Scissors',
    category: 'organize',
    accept: { 'application/pdf': ['.pdf'] },
    acceptLabel: '.pdf',
    multiple: false,
    minFiles: 1,
    options: [
      {
        key: 'splitMode',
        label: 'Split mode',
        type: 'select',
        defaultValue: 'all',
        choices: [
          { value: 'all', label: 'Extract all pages as separate PDFs' },
          { value: 'range', label: 'Extract page range' },
        ],
      },
      {
        key: 'pageRange',
        label: 'Page range (e.g. 1-3, 5)',
        type: 'text',
        placeholder: '1-3, 5, 7-9',
        dependsOn: { key: 'splitMode', value: 'range' },
      },
    ],
    outputExt: '.zip',
    outputMime: 'application/zip',
    color: '#8B5CF6',
  },
  {
    slug: 'compress-pdf',
    name: 'Compress PDF',
    desc: 'Reduce file size while maintaining maximum quality.',
    shortDesc: 'Shrink PDF file size instantly.',
    icon: 'Minimize2',
    category: 'optimize',
    accept: { 'application/pdf': ['.pdf'] },
    acceptLabel: '.pdf',
    multiple: false,
    minFiles: 1,
    options: [
      {
        key: 'quality',
        label: 'Compression level',
        type: 'radio',
        defaultValue: 'medium',
        choices: [
          { value: 'low', label: 'Low compression', hint: 'Best quality' },
          { value: 'medium', label: 'Recommended', hint: 'Balanced' },
          { value: 'high', label: 'High compression', hint: 'Smallest size' },
        ],
      },
    ],
    outputExt: '.pdf',
    outputMime: 'application/pdf',
    color: '#10B981',
  },
  {
    slug: 'pdf-to-word',
    name: 'PDF to Word',
    desc: 'Convert PDF files into fully editable DOCX documents.',
    shortDesc: 'Convert PDF to editable Word.',
    icon: 'FileText',
    category: 'convert',
    accept: { 'application/pdf': ['.pdf'] },
    acceptLabel: '.pdf',
    multiple: false,
    minFiles: 1,
    options: [],
    outputExt: '.docx',
    outputMime: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    color: '#2563EB',
  },
  {
    slug: 'word-to-pdf',
    name: 'Word to PDF',
    desc: 'Convert DOC and DOCX files into universally readable PDFs.',
    shortDesc: 'Convert Word documents to PDF.',
    icon: 'FileOutput',
    category: 'convert',
    accept: {
      'application/msword': ['.doc'],
      'application/vnd.openxmlformats-officedocument.wordprocessingml.document': ['.docx'],
    },
    acceptLabel: '.doc, .docx',
    multiple: false,
    minFiles: 1,
    options: [],
    outputExt: '.pdf',
    outputMime: 'application/pdf',
    color: '#2563EB',
  },
  {
    slug: 'pdf-to-jpg',
    name: 'PDF to JPG',
    desc: 'Convert each PDF page into a high-quality JPG image.',
    shortDesc: 'Export PDF pages as images.',
    icon: 'Image',
    category: 'convert',
    accept: { 'application/pdf': ['.pdf'] },
    acceptLabel: '.pdf',
    multiple: false,
    minFiles: 1,
    options: [
      {
        key: 'dpi',
        label: 'Image quality',
        type: 'radio',
        defaultValue: '150',
        choices: [
          { value: '72', label: 'Small (72 DPI)' },
          { value: '150', label: 'Medium (150 DPI)' },
          { value: '300', label: 'High (300 DPI)' },
        ],
      },
    ],
    outputExt: '.zip',
    outputMime: 'application/zip',
    color: '#F59E0B',
  },
  {
    slug: 'jpg-to-pdf',
    name: 'JPG to PDF',
    desc: 'Convert JPG and PNG images into a single PDF document.',
    shortDesc: 'Turn images into a PDF file.',
    icon: 'Images',
    category: 'convert',
    accept: {
      'image/jpeg': ['.jpg', '.jpeg'],
      'image/png': ['.png'],
    },
    acceptLabel: '.jpg, .jpeg, .png',
    multiple: true,
    minFiles: 1,
    options: [
      {
        key: 'orientation',
        label: 'Page orientation',
        type: 'radio',
        defaultValue: 'portrait',
        choices: [
          { value: 'portrait', label: 'Portrait' },
          { value: 'landscape', label: 'Landscape' },
        ],
      },
      {
        key: 'margin',
        label: 'Margins',
        type: 'radio',
        defaultValue: 'none',
        choices: [
          { value: 'none', label: 'No margin' },
          { value: 'small', label: 'Small' },
          { value: 'big', label: 'Big' },
        ],
      },
    ],
    outputExt: '.pdf',
    outputMime: 'application/pdf',
    color: '#F59E0B',
  },
  {
    slug: 'rotate-pdf',
    name: 'Rotate PDF',
    desc: 'Rotate PDF pages to the correct orientation. Apply to all or specific pages.',
    shortDesc: 'Fix page orientation in your PDF.',
    icon: 'RotateCw',
    category: 'edit',
    accept: { 'application/pdf': ['.pdf'] },
    acceptLabel: '.pdf',
    multiple: false,
    minFiles: 1,
    options: [
      {
        key: 'degrees',
        label: 'Rotation',
        type: 'radio',
        defaultValue: '90',
        choices: [
          { value: '90', label: '90° clockwise' },
          { value: '180', label: '180°' },
          { value: '270', label: '90° counter-clockwise' },
        ],
      },
    ],
    outputExt: '.pdf',
    outputMime: 'application/pdf',
    color: '#06B6D4',
  },
  {
    slug: 'add-watermark',
    name: 'Add Watermark',
    desc: 'Stamp a custom text watermark over your PDF pages.',
    shortDesc: 'Stamp text over your PDF.',
    icon: 'Droplets',
    category: 'edit',
    accept: { 'application/pdf': ['.pdf'] },
    acceptLabel: '.pdf',
    multiple: false,
    minFiles: 1,
    options: [
      {
        key: 'watermarkText',
        label: 'Watermark text',
        type: 'text',
        placeholder: 'CONFIDENTIAL',
        required: true,
      },
      {
        key: 'opacity',
        label: 'Opacity',
        type: 'range',
        defaultValue: '30',
        min: 10,
        max: 80,
        step: 5,
        unit: '%',
      },
      {
        key: 'position',
        label: 'Position',
        type: 'radio',
        defaultValue: 'diagonal',
        choices: [
          { value: 'diagonal', label: 'Diagonal' },
          { value: 'center', label: 'Center' },
          { value: 'top', label: 'Top' },
          { value: 'bottom', label: 'Bottom' },
        ],
      },
    ],
    outputExt: '.pdf',
    outputMime: 'application/pdf',
    color: '#64748B',
  },
  {
    slug: 'page-numbers',
    name: 'Add Page Numbers',
    desc: 'Insert page numbers with custom position, font, and starting number.',
    shortDesc: 'Number pages in your PDF.',
    icon: 'Hash',
    category: 'edit',
    accept: { 'application/pdf': ['.pdf'] },
    acceptLabel: '.pdf',
    multiple: false,
    minFiles: 1,
    options: [
      {
        key: 'position',
        label: 'Position',
        type: 'radio',
        defaultValue: 'bottom-center',
        choices: [
          { value: 'top-left', label: 'Top left' },
          { value: 'top-center', label: 'Top center' },
          { value: 'top-right', label: 'Top right' },
          { value: 'bottom-left', label: 'Bottom left' },
          { value: 'bottom-center', label: 'Bottom center' },
          { value: 'bottom-right', label: 'Bottom right' },
        ],
      },
      {
        key: 'startNumber',
        label: 'Start from page',
        type: 'number',
        defaultValue: '1',
        min: 1,
        max: 9999,
      },
    ],
    outputExt: '.pdf',
    outputMime: 'application/pdf',
    color: '#84CC16',
  },
  {
    slug: 'lock-pdf',
    name: 'Lock PDF',
    desc: 'Protect your PDF with a password. Restrict access and editing.',
    shortDesc: 'Password-protect your PDF.',
    icon: 'Lock',
    category: 'security',
    accept: { 'application/pdf': ['.pdf'] },
    acceptLabel: '.pdf',
    multiple: false,
    minFiles: 1,
    options: [
      {
        key: 'password',
        label: 'Password',
        type: 'password',
        placeholder: 'Enter a strong password',
        required: true,
      },
      {
        key: 'confirmPassword',
        label: 'Confirm password',
        type: 'password',
        placeholder: 'Re-enter password',
        required: true,
      },
    ],
    outputExt: '.pdf',
    outputMime: 'application/pdf',
    color: '#EF4444',
  },
  {
    slug: 'unlock-pdf',
    name: 'Unlock PDF',
    desc: 'Remove PDF password protection to regain full access.',
    shortDesc: 'Remove PDF password restriction.',
    icon: 'Unlock',
    category: 'security',
    accept: { 'application/pdf': ['.pdf'] },
    acceptLabel: '.pdf',
    multiple: false,
    minFiles: 1,
    options: [
      {
        key: 'password',
        label: 'Current password',
        type: 'password',
        placeholder: 'Enter the PDF password',
        required: true,
      },
    ],
    outputExt: '.pdf',
    outputMime: 'application/pdf',
    color: '#22C55E',
  },

  // ─── New Convert Tools ──────────────────────────────────────────────────────
  {
    slug: 'pdf-to-png',
    name: 'PDF to PNG',
    desc: 'Convert each PDF page into a high-quality PNG image with transparency support.',
    shortDesc: 'Export PDF pages as PNG images.',
    icon: 'ImageDown',
    category: 'convert',
    accept: { 'application/pdf': ['.pdf'] },
    acceptLabel: '.pdf',
    multiple: false,
    minFiles: 1,
    options: [
      {
        key: 'dpi',
        label: 'Image quality',
        type: 'radio',
        defaultValue: '150',
        choices: [
          { value: '72', label: 'Small (72 DPI)' },
          { value: '150', label: 'Medium (150 DPI)' },
          { value: '300', label: 'High (300 DPI)' },
        ],
      },
    ],
    outputExt: '.zip',
    outputMime: 'application/zip',
    color: '#06B6D4',
  },
  {
    slug: 'pdf-to-ppt',
    name: 'PDF to PPT',
    desc: 'Convert PDF files into PowerPoint presentations — one slide per page.',
    shortDesc: 'Turn your PDF into a PowerPoint.',
    icon: 'Presentation',
    category: 'convert',
    accept: { 'application/pdf': ['.pdf'] },
    acceptLabel: '.pdf',
    multiple: false,
    minFiles: 1,
    options: [],
    outputExt: '.pptx',
    outputMime: 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
    color: '#F97316',
  },
  {
    slug: 'ppt-to-pdf',
    name: 'PPT to PDF',
    desc: 'Convert PowerPoint PPTX presentations into universally readable PDF files.',
    shortDesc: 'Convert PowerPoint to PDF.',
    icon: 'FileDown',
    category: 'convert',
    accept: {
      'application/vnd.ms-powerpoint': ['.ppt'],
      'application/vnd.openxmlformats-officedocument.presentationml.presentation': ['.pptx'],
    },
    acceptLabel: '.ppt, .pptx',
    multiple: false,
    minFiles: 1,
    options: [],
    outputExt: '.pdf',
    outputMime: 'application/pdf',
    color: '#F97316',
  },
  {
    slug: 'excel-to-pdf',
    name: 'Excel to PDF',
    desc: 'Convert Excel spreadsheets (.xlsx, .xls) into clean, printable PDF documents.',
    shortDesc: 'Convert Excel spreadsheets to PDF.',
    icon: 'Table',
    category: 'convert',
    accept: {
      'application/vnd.ms-excel': ['.xls'],
      'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet': ['.xlsx'],
    },
    acceptLabel: '.xls, .xlsx',
    multiple: false,
    minFiles: 1,
    options: [],
    outputExt: '.pdf',
    outputMime: 'application/pdf',
    color: '#16A34A',
  },
  {
    slug: 'pdf-to-excel',
    name: 'PDF to Excel',
    desc: 'Extract tables and data from PDF files into editable Excel spreadsheets.',
    shortDesc: 'Pull PDF data into Excel.',
    icon: 'Sheet',
    category: 'convert',
    accept: { 'application/pdf': ['.pdf'] },
    acceptLabel: '.pdf',
    multiple: false,
    minFiles: 1,
    options: [],
    outputExt: '.xlsx',
    outputMime: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    color: '#16A34A',
  },
  {
    slug: 'pdf-to-text',
    name: 'PDF to Text',
    desc: 'Extract all text content from your PDF into a plain .txt file.',
    shortDesc: 'Extract text from a PDF file.',
    icon: 'AlignLeft',
    category: 'convert',
    accept: { 'application/pdf': ['.pdf'] },
    acceptLabel: '.pdf',
    multiple: false,
    minFiles: 1,
    options: [],
    outputExt: '.txt',
    outputMime: 'text/plain',
    color: '#78716C',
  },
  {
    slug: 'jpg-to-png',
    name: 'JPG to PNG',
    desc: 'Convert JPG or JPEG images into PNG format with lossless quality.',
    shortDesc: 'Convert JPG images to PNG.',
    icon: 'ArrowRightLeft',
    category: 'convert',
    accept: {
      'image/jpeg': ['.jpg', '.jpeg'],
    },
    acceptLabel: '.jpg, .jpeg',
    multiple: true,
    minFiles: 1,
    options: [],
    outputExt: '.zip',
    outputMime: 'application/zip',
    color: '#A855F7',
  },
  {
    slug: 'png-to-jpg',
    name: 'PNG to JPG',
    desc: 'Convert PNG images into optimised JPG files, with adjustable quality.',
    shortDesc: 'Convert PNG images to JPG.',
    icon: 'ArrowRightLeft',
    category: 'convert',
    accept: {
      'image/png': ['.png'],
    },
    acceptLabel: '.png',
    multiple: true,
    minFiles: 1,
    options: [
      {
        key: 'quality',
        label: 'Output quality',
        type: 'radio',
        defaultValue: '90',
        choices: [
          { value: '70', label: 'Compressed (70%)' },
          { value: '90', label: 'Balanced (90%)' },
          { value: '100', label: 'Maximum (100%)' },
        ],
      },
    ],
    outputExt: '.zip',
    outputMime: 'application/zip',
    color: '#A855F7',
  },

  // ─── New Edit Tools ────────────────────────────────────────────────────────
  {
    slug: 'crop-pdf',
    name: 'Crop PDF',
    desc: 'Remove unwanted margins or trim the visible area of PDF pages.',
    shortDesc: 'Trim margins from your PDF.',
    icon: 'Crop',
    category: 'edit',
    accept: { 'application/pdf': ['.pdf'] },
    acceptLabel: '.pdf',
    multiple: false,
    minFiles: 1,
    options: [
      {
        key: 'marginTop',
        label: 'Top margin (pt)',
        type: 'number',
        defaultValue: '20',
        min: 0,
        max: 200,
      },
      {
        key: 'marginBottom',
        label: 'Bottom margin (pt)',
        type: 'number',
        defaultValue: '20',
        min: 0,
        max: 200,
      },
      {
        key: 'marginLeft',
        label: 'Left margin (pt)',
        type: 'number',
        defaultValue: '20',
        min: 0,
        max: 200,
      },
      {
        key: 'marginRight',
        label: 'Right margin (pt)',
        type: 'number',
        defaultValue: '20',
        min: 0,
        max: 200,
      },
    ],
    outputExt: '.pdf',
    outputMime: 'application/pdf',
    color: '#EC4899',
  },
]

export const CATEGORIES = [
  { id: 'all', label: 'All Tools' },
  { id: 'organize', label: 'Organize' },
  { id: 'optimize', label: 'Optimize' },
  { id: 'convert', label: 'Convert' },
  { id: 'edit', label: 'Edit' },
  { id: 'security', label: 'Security' },
]

export function getToolBySlug(slug) {
  return TOOLS.find(t => t.slug === slug) || null
}

export function getToolsByCategory(category) {
  if (category === 'all') return TOOLS
  return TOOLS.filter(t => t.category === category)
}
